build: off

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      PYTHON_ARCH: "32"
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64
      PYTHON_ARCH: "64"
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda36
      PYTHON_ARCH: "32"
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda36-x64
      PYTHON_ARCH: "64"
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda37
      PYTHON_ARCH: "32"
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda37-x64
      PYTHON_ARCH: "64"
#    - PYTHON_VERSION: 3.8
#      MINICONDA: C:\Miniconda38
#      PYTHON_ARCH: "32"
#    - PYTHON_VERSION: 3.9
#      MINICONDA: C:\Miniconda39-x64
#      PYTHON_ARCH: "64"




init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - '"%MINICONDA%\Scripts\activate.bat"'
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
#  - conda install --yes conda-build
  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  - conda config --add channels conda-forge
#  - conda config --add channels https://conda.anaconda.org/qttesting
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy pytest pytest-runner pytest-pep8 pytest-cov matplotlib pip"

  - activate test-environment
  - conda install -c conda-forge cartopy
  - "python -m pip install --upgrade pip"
  - "python -m pip install --upgrade setuptools"
  - "python -m pip install --upgrade pytest"
  - pip install coverage
  - pip install hypothesis
  - python setup.py install
  - pip install -r requirements.txt"

test_script:
  - coverage run --source=nvector -m py.test build/lib

after_test:
  # If tests are successful, create binary packages for the project.
  # - python setup.py bdist_wheel"
  # - python setup.py bdist_wininst"
  # - python setup.py bdist_msi"
  - ps: "ls dist"

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
#
